# Generated by Django 4.0.4 on 2022-05-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('emailUsuario', models.CharField(max_length=50, verbose_name='email de usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombre de usuario')),
                ('passwordUsuario', models.CharField(max_length=50, verbose_name='nombre de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de mensaje')),
                ('contMensaje', models.CharField(max_length=1000, verbose_name='contenido del mensaje')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.usuario')),
            ],
        ),
    ]
