# Generated by Django 4.0.4 on 2022-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_nombreproducto_categoriaproducto_nombrecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
